// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/LyricTian/gin-admin/v6/internal/app/api"
	"github.com/LyricTian/gin-admin/v6/internal/app/bll/impl/bll"
	"github.com/LyricTian/gin-admin/v6/internal/app/model/impl/gorm/model"
	"github.com/LyricTian/gin-admin/v6/internal/app/router"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	demo := &model.Demo{
		DB: db,
	}
	bllDemo := &bll.Demo{
		DemoModel: demo,
	}
	apiDemo := &api.Demo{
		DemoBll: bllDemo,
	}
	routerRouter := &router.Router{
		DemoAPI: apiDemo,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
		cleanup()
	}, nil
}
